main/urls.py
from django.urls import re_path
from .views import (
    index_view,
    car_type_upload,
    car_model_addition,
    car_parts_upload,
    car_upload,
    car_problem_upload,
    data_query,
    car_type_filter,
)

urlpatterns = [
    re_path('^$',index_view,name='index_view'),
    re_path('^UploadCarType/$',car_type_upload,name='upload-car-type'),
    re_path('^UploadCarModel/$',car_model_addition,name="upload-car-model"),
    re_path('^CarPartUpload/$',car_parts_upload,name="upload-car-part"),
    re_path('^CarUpload/$',car_upload,name="car-upload"),
    re_path('^CarProplemUpload/$',car_problem_upload,name="car-problem-upload"),
    re_path('^DataQuery/$',data_query,name="data-query"),
    re_path('^filtercartype/$',car_type_filter,name="filter-car-type")
]

under_the_hood/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path,re_path,include
from users import views as user_views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    re_path('^admin/', admin.site.urls),
    re_path('^register/',user_views.register,name="register"),
    re_path('^profile/',user_views.profile,name="profile"),
    re_path('',include('main.urls')),
    re_path('^login/',auth_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    re_path('^logout',auth_views.LogoutView.as_view(template_name='users/logout.html'),name='logout')
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.contrib.auth.models import User

class Car_Type(models.Model):
    '''
    This class will hold the diffrent types of cars their are e.g(Toyota,Subaru,Audi)
    '''
    car_type_logo = models.ImageField(upload_to="car_type_logos",default="default_logo.jpg")
    car_type_name = models.CharField(max_length=255)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.car_type_name

class Car_Model(models.Model):
    '''
    This class will hold the diffrent types of models for the car their are e.g(Subaru legacy,Toyota camri,Toyota fielder)
    '''
    car_model_image = models.ImageField(upload_to='car_model_images',default='default_car_model.jpg',blank=True)
    car_model_name = models.CharField(max_length=200)
    verson = models.IntegerField()
    car_type = models.ForeignKey(Car_Type,on_delete=models.CASCADE)
    date_realised = models.DateField()

    def __str__(self):
        return f"{self.car_model_name}(Version {self.verson}) from {self.car_type.car_type_name} brand"

class Car(models.Model):
    '''
    This class will contain the specific details of a certain car
    '''
    car_image = models.ImageField(upload_to='car_images',blank=True,default="default_car.jpg")
    owner = models.ForeignKey(User,on_delete=models.CASCADE)
    registration_number = models.CharField(max_length=10)
    car_type = models.ForeignKey(Car_Type,on_delete=models.CASCADE)
    model = models.ForeignKey(Car_Model,on_delete=models.CASCADE)
    mileage = models.BigIntegerField(default=0)
    date_bought = models.DateField()
    
    def __str__(self):
        return f"{self.owner.username} Car of type {self.car_type.car_type_name}"


class Part(models.Model):
    '''
    This class will contain the parts class for diffrent parts of a car e.g(wheels,engine,body)
    '''
    part_image = models.ImageField(upload_to='part_images',default='default_car_part.jpg',blank=True)
    part_name = models.CharField(max_length=40)
    
    def __str__(self):
        return self.part_name

class Problem(models.Model):
    '''
    This class will contain the problems that are associated with that car
    '''
    problem_name = models.CharField(max_length=40)
    problem_description = models.TextField()
    part = models.ForeignKey(Part,on_delete=models.CASCADE)
    fix = models.TextField()
    car = models.ForeignKey(Car,on_delete=models.CASCADE)
    notes = models.TextField(blank=True)
    date_entry = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.problem_name

main/forms.py
from django import forms
from .models import (
    Car_Type,
    Car_Model,
    Car,
    Part,
    Problem,
)

class Car_Type_Form(forms.ModelForm):
    '''
    Form for uploading the car type from (Toyota,Subs)
    '''
    class Meta:
        model = Car_Type
        fields = ('car_type_logo','car_type_name','description')

class Car_Model_Form(forms.ModelForm):
    '''
    Form for uploading the car model from a car type
    '''
    car_type = forms.ModelChoiceField(queryset=Car_Type.objects.all())
    class Meta:
        model = Car_Model
        fields = ('car_model_image','car_type','car_model_name','verson','date_realised')

class Car_Upload_Form(forms.ModelForm):
    '''
    Form for uploading the users car
    '''
    class Meta:
        model = Car
        fields = ('car_image','registration_number','car_type','model','mileage','date_bought')

class Part_Upload_Form(forms.ModelForm):
    '''
    Form for uploading car parts
    '''
    class Meta:
        model = Part
        fields =('part_image','part_name')

class Problem_Upload(forms.ModelForm):
    '''
    Form for uploading a car problem
    '''
    part = forms.ModelChoiceField(queryset=Part.objects.all())
    class Meta:
        model = Problem
        fields = ('problem_name','problem_description','part','fix','car','notes')

    def __init__(self, user, *args, **kwargs):
        super(Problem_Upload, self).__init__(*args, **kwargs)
        self.fields['car'].queryset = Car.objects.filter(owner=user)

main/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from .forms import (
    Car_Type_Form,
    Car_Upload_Form,
    Car_Model_Form,
    Part_Upload_Form,
    Problem_Upload
)
from .models import (
    Car_Type,
    Car_Model,
    Car,
    Part,
    Problem
)

def index_view(request):
    '''
    Will render the home page
    '''
    context = {
        "title":"Home"
    }
    return render(request,'main/index.html',context)

@login_required
def car_type_upload(request):
    '''
    This view function will help in uploading of a car type
    '''
    car_types = Car_Type.objects.all()
    # car_models = Car_Model.objects.all()
    if request.method == 'POST':
        form = Car_Type_Form(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            return redirect(car_type_upload)
    else:
        form = Car_Type_Form()
    
    context = {
        "title":"upload car type",
        "form":form,
        "car_types":car_types,
        # "car_models":car_models
    }
    return render(request,"main/car_type_upload_form.html",context)

@login_required
def car_model_addition(request):
    '''
    This view will upload the car model type
    '''
    car_models = Car_Model.objects.all()
    if request.method == 'POST':
        form = Car_Model_Form(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            return redirect(car_model_addition)
    else:
        form = Car_Model_Form()
    context = {
        "title":"upload car model",
        "form":form,
        "car_models":car_models
    }
    return render(request,"main/car_model_upload_form.html",context)

@login_required
def car_parts_upload(request):
    '''
    This view will enable upload of parts
    '''
    car_parts = Part.objects.all()
    if request.method == 'POST':
        form = Part_Upload_Form(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            return redirect(car_parts_upload)
    else:
        form = Part_Upload_Form()
    
    context = {
        "title":"car part upload",
        "form":form,
        "car_parts":car_parts
    }
    return render(request,"main/car_part_upload.html",context)

@login_required
def car_upload(request):
    '''
    This view will handle the specific car upload
    '''
    if request.method == 'POST':
        form = Car_Upload_Form(request.POST,request.FILES)
        if form.is_valid():
            car = form.save(commit=False)
            car.owner = request.user
            car.save()
            return redirect(car_upload)
    else:
        form = Car_Upload_Form()
    
    context = {
        "title":"car upload",
        "form":form
    }
    return render(request,"main/car_upload_form.html",context)

@login_required
def car_problem_upload(request):
    '''
    This view will handle the form for uploading a car problem
    '''
    if request.method == 'POST':
        form = Problem_Upload(request.user,request.POST)
        if form.is_valid():
            form.save()
            return redirect(car_problem_upload)
    else:
        form = Problem_Upload(request.user)
    
    context = {
        "title":"car problem upload",
        "form":form
    }

    return render(request,"main/car_problem_upload.html",context)

@login_required
def data_query(request):
    '''
    Will house the functionality searching for the data that one wants
    '''
    car_types = Car_Type.objects.all()

    context = {
        "title":"Data center",
        "car_types":car_types
    }
    return render(request,"main/data_query.html",context)

@login_required
def car_type_filter(request):
    '''
    Will render the page with the cartype so as to be able to search for specific model car
    '''
    if 'car' in request.GET and request.GET.get('car'):
        filterd_car = request.GET.get('car')
        car_type = Car_Type.objects.filter(car_type_name__icontains=filterd_car)
        car_models = Car_Model.objects.filter(car_type__car_type_name__icontains=filterd_car)
        car_problems = Problem.objects.filter(car__car_type__car_type_name__icontains=filterd_car)
    context = {
        "title":"car type",
        "car_type":car_type,
        "car_models":car_models,
        "car_problems":car_problems
    }
    return render(request,"main/car_type_filter.html",context)

main/templates/main/base.html
{% load bootstrap4 %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    {% block styles %}
        {% bootstrap_css %}
        <link href="https://fonts.googleapis.com/css?family=Satisfy&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'css/main.css' %}">
    {% endblock %}

    {% if title %}
    <title>Under The Hood - {{ title }}</title>
    {% else %}
    <title>Under The Hood</title>
    {% endif %}

</head>
<body>
    {% include 'main/navbar.html' %}
    
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
    
    {% block content %}

    {% endblock %}

    {% block scripts %}
        {% bootstrap_javascript jquery='full' %}
    {% endblock %}
</body>
</html>

main/templates/main/car_model_upload_form.html
{% extends 'main/base.html' %}
{% load crispy_forms_tags %}


{% block content %}
<div class="container">
<div class="row">
    <div class="col-md-6">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="boarder-bottom mb-4">Upload a car model</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Upload</button>
            </div>
        </form>
    </div>
</div>
<div class="col-md-6"></div>
</div>
</div>
{% endblock %}

main/templates/main/car_part_upload.html
{% extends 'main/base.html' %}
{% load crispy_forms_tags %}


{% block content %}
<div class="container">
<div class="row">
    <div class="col-md-6">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="boarder-bottom mb-4">Upload a car Part</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Upload</button>
            </div>
        </form>
    </div>
</div>
<div class="col-md-6"></div>
</div>
</div>
{% endblock %}

main/templates/main/car_problem_upload.html
{% extends 'main/base.html' %}
{% load crispy_forms_tags %}


{% block content %}
<div class="container">
<div class="row">
    <div class="col-md-6">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="boarder-bottom mb-4">Upload Car Problem</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Upload</button>
            </div>
        </form>
    </div>
</div>
<div class="col-md-6"></div>
</div>
</div>
{% endblock %}

main/templates/main/car_type_filter.html
{% extends 'main/base.html' %}

{% block content %}

<div class="container">
    <h2 class="heading">{{ car_type.car_type_name }}</h2>
    <p>{{ car_type.description }}</p>
    
    <h1 class="heading">Problems Associated</h1>

    
    <p>Filter By Model</p>
    <form action="{#% url 'filter-model-type' %}" class="form-style">
            <div class="form-group">
                <label for="CarModel">Car model filter</label>
                <select id="CarModel" class="form-control" name="carmodel">
                    {% for car_model in car_models %}
                    <option>{{ car_model.car_model_name }} :Version {{ car_model.verson }}</option>
                    {% endfor %}
                </select><br>
                <button class="btn btn-outline-primary" type="submit">Filter</button>
            </div>
    </form>
    <div class="row">
    {% for problem in car_problems %}
    <div class="col-md-4">
    <div class="card" style="width: 18rem;">
            <img src="{{ problem.car.car_image.url }}" class="card-img-top" alt="{{ problem.car.model.car_model_name }} image">
            <div class="card-body">
              <h5 class="card-title">Problem: {{ problem.problem_name }}</h5>
              <p class="card-text"><strong>Descrition:</strong>  {{ problem.problem_description }}</p>
              <p class="card-text"><strong>Car Type:</strong> {{ problem.car.model.car_model_name }} Version:{{ problem.car.model.verson }}</p>
              <!-- <a href="#" class="btn btn-primary">See car details</a> Future Implementation-->
            </div>
          </div>
        </div>
        {% endfor %}
        </div>
</div>

{% endblock %}

main/templates/main/car_type_upload_form.html
{% extends 'main/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="boarder-bottom mb-4 heading">Upload a Car Type</legend>
                    {{ form|crispy }}
                </fieldset>
                <div class="form-group">
                    <button class="btn btn-outline-info" type="submit">Upload</button>
                </div>
            </form>
        </div>
        <div class="col-md-6">
            <h1 class="heading">Car Types Available</h1>
            <p><strong>N.B</strong> Please ensure the car type you are entering does not exist</p>
            {% for cartype in car_types %}
                    <p>{{ forloop.counter }} : {{ cartype.car_type_name }}</p>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/car_upload_form.html
{% extends 'main/base.html' %}
{% load crispy_forms_tags %}


{% block content %}
<div class="container">
<div class="row">
    <div class="col-md-6">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="boarder-bottom mb-4">Upload A Car</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Upload</button>
            </div>
        </form>
    </div>
</div>
<div class="col-md-6"></div>
</div>
</div>
{% endblock %}

main/templates/main/data_query.html
{% extends 'main/base.html' %}

{% block content %}

    <div class="container">
        <div>
            <h1 class="text-center heading">Data Center</h1><hr>
            <h2 class="heading">Description</h2><hr>
            <p>This page is all about the data you want may it be specific car data general data or summary data</p>
        </div>
        <h2 class="heading">Data and analytics</h2><hr>

        <h3 class="heading">Filter For Data Results</h3><hr>
        <div class="row">
            <div class="col-md-4">
                <h4 class="heading">Filter Based On Car Type</h4>
                <form action="{% url 'filter-car-type' %}" class="form-style">
                        <div class="form-group">
                            <label for="CarFilter">Car data filter</label>
                            <select id="CarFilter" class="form-control" name="car">
                                {% for car_type in car_types %}
                                <option>{{ car_type.car_type_name }}</option>
                                {% endfor %}
                            </select><br>
                            <button class="btn btn-outline-primary" type="submit">Filter</button>
                        </div>
                </form>
            </div>

            <div class="col-md-4">
                    <h4 class="heading">Search By Owner Or Garage</h4>

            </div>

            <div class="col-md-4">

            </div>
        </div>
        <h3 class="heading">Cars we have data on</h3><hr>
        <div class="row">
        {% for car_type in car_types %}
        <div class="col-md-4">
                <div class="card" style="width: 18rem;">
                        <img class="card-img-top" src="{{ car_type.car_type_logo.url }}" alt="{{car_type.car_type_logo.url}}">
                        <div class="card-body">
                          <h5 class="card-title">{{ car_type.car_type_name }}</h5>
                          <h6>Car Models Available</h6>
                          {% for car_model in car_type.car_model_set.all %}
                                <p class="card-text">{{ forloop.counter }}. {{ car_model.car_model_name }} version {{ car_model.verson }}</p>
                        {% endfor %}
                          <!-- <a href="#" class="btn btn-primary">Go somewhere</a> future implementation data on the car type-->
                        </div>
                      </div>
        </div>
        {% endfor %}
    </div><hr>
    </div>

{% endblock %}

main/templates/main/index.html
{% extends 'main/base.html' %}

{% block content %}

<div id="index-landing">
    <div id="overlay">
        <div class="text-center" id="index-placing">
        <h2>Welcome To Under The Hood</h2>
        <button class="btn btn-primary">Sign Up</button>
        </div>
    </div>
</div><br>
<hr>
<div class="container-fluid">
    <h1 class="text-center heading">Why Us</h1>
    <ol>
        <li>Advantages of using this site is that you are able to use it if you want to get data on a particular
            car that you want to buy as a second hand vehicle and decide whether you want to buy it.</li>  
        <li>
            To researchers and car companys one is able to determine the problems associated with a certain car
            and they are able to improve the design or recall the vehicle all together.
        </li>
        <li>
            To car Owners one is able to keep track of the problem their cars have and incase that issue should arise
            again they are able to determine what is the cause
        </li>
        <li>
            To buisness owners one is able to determine the most probable breakdown of a certain car and buy spare
            parts that will move out of the shelf quickly
        </li>
    </ol>
</div><br><hr>
<div class="container-fluid">
    <h1 class="text-center heading">How It Works</h1>
    <div class="row">
        <div class="col-md-6">
            <div id="how-it-works-image">
                <div id="how-it-works-overlay">

                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div id="how-it-works-background">

            </div>
        </div>
    </div>
</div><br><hr>
<div class="container-fluid">
<h1 class="text-center heading">About Us</h1>
    <div class="text-center">
        <p>
            We are a company that aims at providing accurate data about cars and their problems.We handle data
            from individuals and garadges.
        </p>
    </div><br>
</div>
{% endblock %}

main/templates/main/navbar.html
<!--Navbar -->
<nav class="mb-1 navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <a class="navbar-brand" href="/"><i class="fa fa-car-hood"></i> Under The Hood</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-4"
        aria-controls="navbarSupportedContent-4" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    {% if user.is_authenticated %}
    <div class="collapse navbar-collapse" id="navbarSupportedContent-4">
        <ul class="navbar-nav ml-auto">
            <!-- <form class="navbar-form" role="search" action="">
                <div class="input-group">
                <input type="text" class="form-control" placeholder="Search Car" name="buisness">
                    <div class="input-group-btn">
                        <button class="btn btn-outline-info" type="submit">Search</button>
                    </div>
                </div>
              
            </form> -->
            <li class="nav-item">
                    <a class="nav-link" href="{% url 'data-query' %}">Data Center</a>
                </li>
            <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink-4" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-user"></i> Upload </a>
                    <div class="dropdown-menu dropdown-menu-right dropdown-info" aria-labelledby="navbarDropdownMenuLink-4">
                        <a class="dropdown-item" href="{% url 'upload-car-type' %}">Car Type</a>
                        <a class="dropdown-item" href="{% url 'upload-car-model' %}">Car Model</a>
                        <a class="dropdown-item" href="{% url 'upload-car-part' %}">Car Part</a>
                        <a class="dropdown-item" href="{% url 'car-problem-upload' %}">Car Problem</a>
                        <a class="dropdown-item" href="{% url 'car-upload' %}">Car Upload</a>
                    </div>
                </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink-4" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-user"></i> Profile </a>
                <div class="dropdown-menu dropdown-menu-right dropdown-info" aria-labelledby="navbarDropdownMenuLink-4">
                    <a class="dropdown-item" href="{% url 'profile' %}">My account</a>
                    <a class="dropdown-item" href="{% url 'logout' %}">Log out</a>
                </div>
            </li>
        </ul>
    </div>
    {% else %}
    <div class="collapse navbar-collapse" id="navbarSupportedContent-4">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink-4" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-user"></i> Account </a>
                <div class="dropdown-menu dropdown-menu-right dropdown-info" aria-labelledby="navbarDropdownMenuLink-4">
                    <a class="dropdown-item" href="{% url 'login' %}">Log In</a>
                    <a class="dropdown-item" href="{% url 'register' %}">Sign Up</a>
                </div>
            </li>
        </ul>
    </div>
    {% endif %}
</nav>
<!--/.Navbar -->